# Generated by Django 4.2.4 on 2023-08-04 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('City_Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('Province_Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('User_Id', models.BigAutoField(auto_created=True, db_column='User_Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('streetaddress', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.city')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.province')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('User_Id', models.OneToOneField(db_column='User_Id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='seller.seller')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
