# Generated by Django 4.2.4 on 2023-08-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_category_productadd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
