# Generated by Django 4.2.4 on 2023-08-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_rename_name_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadd',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
