# Generated by Django 4.2.4 on 2023-08-05 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_productadd_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productadd',
            new_name='addproduct',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
