# Generated by Django 4.2.3 on 2023-07-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_login_user_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
